platform :ios, '8.0'
target 'SWJSQQSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'Alamofire', '~> 4.7'
  pod 'SnapKit', '~> 4.0.0'
  use_frameworks!
  # Pods for SWJSQQSDK
end
target 'SWJSQQSDKDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWJSQQSDKDemo

end
