#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Thu Feb 14 10:33:47 CST 2019
#define hx_AES128DecryptWithKey AES128DecryptWithKeyhfvgpupAndlrmefrj
#define hx_AES128EncryptWithKey AES128EncryptWithKeynjflssgAndicejqwr
#define hx_Regisdevicebygame RegisdevicebygamerjoqpvuAndcnkdbee
#define hx_changeloginviewheight changeloginviewheightrhkkshbAndjxpmjwz
#define hx_decodeWithIV decodeWithIVoaqefnuAndikthyeo
#define hx_encryptWithIV encryptWithIVdjsampzAndvhrzijq
#define hx_gamelogin gameloginstvaqbuAndehfwvvp
#define hx_getHost getHostxaswyguAndxgrzqjs
#endif
