source 'https://github.com/cocoapods/specs.git'
platform :ios, '10.0'
inhibit_all_warnings!
use_modular_headers!

target 'fxxproject' do
    pod 'AFNetworking',:modular_headers => false
    # H5 与 原生 交互
    pod 'WebViewJavascriptBridge'
    pod 'MJExtension'
    pod 'MBProgressHUD'
    pod 'IQKeyboardManager'
end
